name: "Test"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ${{ matrix.host }}
    name: ${{ matrix.name }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: ubuntu-latest
            name: Linux
          - host: macos-26-intel
            name: macOS
          - host: windows-latest
            name: Windows (ld)
            linker: ld
          - host: windows-latest
            name: Windows (link.exe)
            linker: link.exe
          - host: windows-latest
            name: Windows (lld-link.exe)
            linker: lld-link.exe

    steps:
      - uses: actions/checkout@v6
      - name: Setup NASM
        uses: ilammy/setup-nasm@v1
      - name: Setup MSVC
        if: matrix.linker == 'link.exe' || matrix.linker == 'lld-link.exe'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Print NASM version
        run: nasm -v
      - uses: actions/setup-python@v6
        with:
            python-version: '3.13'
      - run: python -m pip install -U pytest
      - run: make test NASM_LINKER=${{ matrix.linker }}
